import Foundation

/// Renders `_INDEX.md`, the index of the whole archive: every folder in its place in the tree. Machine-owned.
public enum IndexFile {
    public static func render(snapshot: TaxonomySnapshot, generatedAt: Date) -> String {
        let documents = snapshot.folders.reduce(0) { $0 + $1.documentCount }
        var out = """
        ---
        arrumator: \(AboutFile.schemaVersion)
        kind: index
        generated: "\(generatedAt.formatted(.iso8601))"
        folders: \(snapshot.folders.count)
        documents: \(documents)
        ---
        # Archive index
        Generated by Arrumator. Do not edit this file; edit the `_about.md` inside a folder instead.

        ## Tree

        """
        for (folder, depth) in snapshot.outline() {
            var facts: [String] = []
            if folder.documentCount > 0 { facts.append(Format.count(folder.documentCount, "document")) }
            if folder.yearSubfolders { facts.append(folder.yearRule == .fiscalPeriod ? "by fiscal year" : "by year") }
            let purpose = firstSentence(folder.description)
            out += String(repeating: "  ", count: depth - 1) + "- **\(folder.name)**" + (purpose.isEmpty ? "" : " — \(purpose)")
                + (facts.isEmpty ? "" : " (\(facts.joined(separator: ", ")))") + "\n"
        }
        let learned = snapshot.folders.filter { !$0.learnedExamples.isEmpty || !$0.learnedCorrespondents.isEmpty }
        if !learned.isEmpty {
            out += "\n## Learned from use\n"
            for folder in learned {
                var parts: [String] = []
                if !folder.learnedCorrespondents.isEmpty { parts.append("usual correspondents: " + folder.learnedCorrespondents.joined(separator: ", ")) }
                if !folder.learnedExamples.isEmpty { parts.append("recent: " + folder.learnedExamples.joined(separator: "; ")) }
                out += "- \(snapshot.path(of: folder)) — \(parts.joined(separator: " · "))\n"
            }
        }
        out += """

        ## Conventions
        - The tree takes the shape the archive's logic describes, and file names follow it too.
        - A `YYYY` folder holds a folder's documents of one year: the document date, or for folders filed by fiscal year the period the document refers to.
        - Folders are created on demand as documents arrive; each one's `_about.md` says what belongs there.

        """
        return out
    }

    private static func firstSentence(_ s: String) -> String {
        let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
        if let r = trimmed.range(of: ". ") { return String(trimmed[..<r.lowerBound]) + "." }
        return trimmed
    }
}
