import Foundation

/// Renders `_INDEX.md`, the Johnny.Decimal index of the whole archive. Machine-owned.
public enum IndexFile {
    public static func render(snapshot: TaxonomySnapshot, generatedAt: Date) -> String {
        let categories = snapshot.folders.filter { $0.kind == .category }
        let documents = categories.reduce(0) { $0 + $1.documentCount }
        var out = """
        ---
        arrumator: \(AboutFile.schemaVersion)
        kind: index
        generated: "\(generatedAt.formatted(.iso8601))"
        areas: \(snapshot.areas.count)
        categories: \(categories.count)
        documents: \(documents)
        ---
        # Archive index
        Generated by Arrumator. Do not edit this file; edit the `_about.md` inside a folder instead.

        ## Tree
        | Code | Folder | Years | Purpose | Docs |
        |---|---|---|---|---|

        """
        for area in snapshot.areas {
            out += "| **\(area.code)** | \(escape(area.name)) | | \(escape(firstSentence(area.description))) | |\n"
            for cat in snapshot.children(of: area.code) {
                let years = cat.yearSubfolders ? (cat.yearRule == .fiscalPeriod ? "YYYY (fiscal)" : "YYYY") : "–"
                out += "| \(cat.code) | \(escape(cat.name)) | \(years) | \(escape(firstSentence(cat.description))) | \(cat.documentCount) |\n"
            }
        }
        let learned = categories.filter { !$0.learnedExamples.isEmpty || !$0.learnedCorrespondents.isEmpty }
        if !learned.isEmpty {
            out += "\n## Learned from use\n"
            for cat in learned {
                var parts: [String] = []
                if !cat.learnedCorrespondents.isEmpty { parts.append("usual correspondents: " + cat.learnedCorrespondents.joined(separator: ", ")) }
                if !cat.learnedExamples.isEmpty { parts.append("recent: " + cat.learnedExamples.joined(separator: "; ")) }
                out += "- \(cat.code) \(cat.name) — \(parts.joined(separator: " · "))\n"
            }
        }
        out += """

        ## Conventions
        - Path: `Area / Category / [YYYY] / file`; never deeper.
        - Filename: `YYYY-MM-DD Correspondent - Doc Type - Title.ext`
        - Year folder = document date, except categories marked "fiscal", where it is the period the document refers to.
        - Folders are created on demand as documents arrive; each one's `_about.md` says what belongs there.

        """
        return out
    }

    private static func escape(_ s: String) -> String { s.replacingOccurrences(of: "|", with: "\\|") }

    private static func firstSentence(_ s: String) -> String {
        let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
        if let r = trimmed.range(of: ". ") { return String(trimmed[..<r.lowerBound]) + "." }
        return trimmed
    }
}
