import ArrumatorCore
import ArrumatorExtract
import Foundation
import Testing

/// The synthetic corpus in `Tests/Fixtures`, generated by `Tools/FixtureGen`, read as the app reads it, against the
/// ground truth in its `expected.json`: every document that carries its own text gives the words its title holds and
/// the warnings it was made to raise. Scans and photos, which only OCR reads, are checked by `fixturegen --verify` and
/// measured by `arrumatorcli eval`.
@Suite("The fixture corpus")
struct FixtureCorpusTests {
    /// One entry of `expected.json`, as much of it as these tests read.
    struct Fixture: Decodable, Sendable, CustomTestStringConvertible {
        struct Expected: Decodable, Sendable {
            let titleContains: [String]
            let warnings: [WarningCode]?
        }

        let file: String
        let kind: String
        let duplicateOf: String?
        let expected: Expected

        var testDescription: String { file }
    }

    private struct Manifest: Decodable {
        let fixtures: [Fixture]
    }

    /// The kinds whose text is in the file itself rather than in an image of it.
    private static let textKinds: Set = ["pdf-text", "docx", "xlsx", "eml", "text"]
    static let corpus = URL(filePath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
        .appending(path: "Fixtures", directoryHint: .isDirectory)

    /// The corpus's documents that carry their own text, each once: an exact copy is a test of duplicates, not of reading.
    static func textDocuments() throws -> [Fixture] {
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        let manifest = try decoder.decode(Manifest.self, from: Data(contentsOf: corpus.appending(path: "expected.json")))
        return manifest.fixtures.filter { textKinds.contains($0.kind) && $0.duplicateOf == nil }
    }

    private let registry: ExtractorRegistry

    init() throws { registry = try TestConfig.registry() }

    @Test("the corpus holds documents of every kind that carries its own text")
    func corpusIsThere() throws {
        let kinds = Set(try Self.textDocuments().map(\.kind))
        #expect(kinds == Self.textKinds, "a corpus missing a kind would leave its reader untested here")
    }

    @Test("a document with its own text gives the words its title holds and the warnings it was made to raise",
          arguments: try FixtureCorpusTests.textDocuments())
    func readsWhatTheGroundTruthSays(_ fixture: Fixture) async throws {
        let url = Self.corpus.appending(path: fixture.file)
        let content = try await registry.extract(url, sha256: fixture.file, context: try TestConfig.context(), trace: .disabled)
        let expectedWarnings = Set(fixture.expected.warnings ?? [])
        if !expectedWarnings.isDisjoint(with: [.encrypted, .corrupted]) {
            #expect(expectedWarnings.isSubset(of: content.warnings.map(\.code)),
                    "a file that cannot be opened says why: \(content.warningSummary)")
            return
        }
        let text = Self.folded(content.text)
        let missing = fixture.expected.titleContains.filter { !text.contains(Self.folded($0)) }
        #expect(missing.isEmpty, "every word of the title is in the text read from the file, but not \(missing)")
        #expect(content.textOrigin == .textLayer, "the file's own text is read, with no OCR")
        #expect(expectedWarnings.isSubset(of: content.warnings.map(\.code)),
                "the warnings the file was made to raise are raised: \(content.warningSummary)")
    }

    /// Compared as `fixturegen --verify` compares: ignoring case, accents, width and how words are spaced.
    private static func folded(_ text: String) -> String {
        text.folding(options: [.caseInsensitive, .diacriticInsensitive, .widthInsensitive], locale: Locale(identifier: "en_US_POSIX"))
            .split(whereSeparator: \.isWhitespace).joined(separator: " ")
    }
}
